### ISSUE TITLE
"Add tweet" looks crappy on small screens

### ISSUE THREAD

**Issue by itsexe** [itsexe/Chirpy_Frontend#3]
On screens with a resolution lower than 1024*XXX, the "add tweet" area looks not very nice.

![ss 2015-03-20 at 08 45 02](https://cloud.githubusercontent.com/assets/9327096/6759707/5cc1de1a-cf42-11e4-8cb5-58211f1ce292.png)

**Comment by zzyn-me** [comment]
I'll fix it soon.
